export default (key) => ({
  'credentials_do_not_match_records': 'These credentials do not match our records.',
  'provider_password_is_incorrect': 'The provided password is incorrect.',
  'failed': 'These credentials do not match our records.',
  'too_many_login_attempts': 'Too many login attempts. Please try again in :seconds seconds.',
  'logout': 'Logout',
  'log_in': 'Log in',
  'already_registered': 'Already registered?',
  'register': 'Register',
  'forgot_your_password': 'Forgot your password?',
  'remember_me': 'Remember me',
  'email': 'Email',
  'password': 'Password',
  'need_an_account': 'Need an account?',
  'verify_email_disclaimer': "Thanks for signing up! Before getting started, could you verify your email address by clicking on the link we just emailed to you? If you didn't receive the email, we will gladly send you another.",
  'name': 'Name',
  'email': 'Email',
  'password': 'Password',
  'confirm_password': 'Confirm Password',
  'resend_verification_email': 'Resend Verification Email',
}[key.replace('auth.', '')] || key)